data_setting:
#  h: 224
#  w: 224
#  pad: 0

  #version1 about data_argument:
  DA: false
  rr: uav
  cj: 'no'
  ra: satellite
  re: satellite
  #version2 about data_argument:
  uav_da: ['rr',]
  sat_da: ['ra','re']

  erasing_p: 0.3
  imgsize2net: 224
  satimgsize2crop: 256
  n_rand2sample_per_pos: 1

exp_setting:
  exp_name: debug3_gta_vitb_224
  load2test: /home/data/zwk/pyproj_DUAV_salad_6.4/exps/exp_wohead_vit-b/epoch000.pth
  load2train: ''
#  p_satinfo_json: /home/data/zwk/data_uavimgs_XianganXmu__512h_lineClassed/dataset_xmu_meta/satimg_xiangan_xmu5km2_03res_info.json
#  p_uavinfo_json: /home/data/zwk/data_uavimgs_XianganXmu__512h_lineClassed/dataset_xmu_meta/uavimgs_xiangan_xmu_info.json
#  dataset_name: 'xmu'
  p_satinfo_json: /home/data/zwk/dataset_Game4Loc/satmap_info.json
  p_uavinfo_json: /home/data/zwk/dataset_Game4Loc/cross-area-drone2sate-train.json
  dataset_name: gta
  save_freq: 1
  tensorboard: true
  val: True
  val_freq: 1

hardware_setting:
  autocast: true
  batchsize: 32
  gpu_ids: '0'
  num_worker: 10

learning_setting:
  droprate: 0.5
  lr_sched:
    gamma: 0.95
    milestones:
    - 35
    - 45
    name: multistep
  num_epochs: 50
  optimizer:
    lr: 0.01
    momentum: 0.9
    name: sgd
    nesterov: true
    weight_decay: 0.0005
  warm_epoch: 0

network_setting:
  backbone: ViTB-224
  block: 2
  cls_loss: CELoss
  feature_loss:
  - WeightedSoftTripletLoss_v3
  head: ''
  head_pool: avg
  kl_loss: KLLoss
  norm_output: true
  num_bottleneck: 512
  w_classify: false
