Data Augmentation Settings:
  DA: false
  cj: 'no'
  erasing_p: 0.3
  h: 224
  pad: 0
  ra: satellite
  re: satellite
  rr: uav
  w: 224
Experiment Settings:
  data_dir: /home/data/zwk/dataset_DenseUAV/train
  exp_name: exp5
  load_from: ' '
  save_freq: 10
  tensorboard: true
  val: true
  val_freq: 200
Hardware Settings:
  autocast: true
  batchsize: 160
  gpu_ids: '0'
  num_worker: 8
Learning Settings:
  droprate: 0.5
  lr: 0.01
  num_epochs: 120
  warm_epoch: 0
Network Settings:
  backbone: ViTB-224
  block: 2
  cls_loss: CELoss
  feature_loss: WeightedSoftTripletLoss
  head: FSRA
  head_pool: avg
  kl_loss: KLLoss
  num_bottleneck: 512
  sample_num: 1
