exp_setting:
  dir2save_log: gen_fm_exps/logs  # 相对于项目根目录
  dir2save_ckpt: gen_fm_exps/ckpts  # 相对于项目根目录
  exp_name: stage1_visloc_splitInterval82_tripleLoss_singleEdge_hardest_fm_mask_dinov2B2 #tripleLoss_singleEdge_hardest_fm_mask
  save_freq: 1
  tensorboard: True
  val: False
  val_freq: 1

  # load2test: 继续训练或测试时加载的checkpoint（字符串路径）
  load2test: ""

  # load2train: 继续训练时加载的checkpoint（字符串路径）
  load2train: "/home/data/zwk/pyproj_neuloc_v0/gen_fm_exps/ckpts/stage1_visloc_splitInterval82_tripleLoss_singleEdge_hardest_fm_mask_dinov2B2/epoch005.pth"

# ==================== 数据加载配置 ====================
data_setting:
  pad_mode: "zeros" #"zeros" or
  imgsize2net: 224
  satimgsize2crop: 244   #satimgsize2crop：res02m:zuchwil=540,zurich=614; res03m:zuchwil=400; res05m:zurich=224
  add_random_satimg_negs: True
  n_rand2sample_per_pos: 256 #16
  sat_as_query: False #sat_as_query数量=batchsize_uav
  split_train_ratio: 0.8
  split_mode: interval

# ==================== 场景配置 ====================
# 场景列表（支持任意数量）：
# - 当列表只有1个场景时，程序自动使用单场景模式
# - 当列表有多个场景时，程序自动使用多场景模式
# 采样策略（仅在多场景时生效）：
# - "round_robin": 循环轮流采样各场景
# - "random": 随机选择场景
# - "weighted": 根据场景权重加权采样
scenes_setting:
  sampling_strategy: "weighted"
  # 场景列表（变长）
#  dataset_name: neuloc
#  scenes:
#    - name: "zurich"
#      p_satinfo_json: /home/data/zwk/data_uavimgs_wingtra/Zurich/zurich_blocks12_proj2056_res03m.json
#      p_uavinfo_json: /home/data/zwk/data_uavimgs_wingtra/Zurich/uavimgs_info/uavimgs_metainfo.json
#      p_uav_geocsv: /home/data/zwk/data_uavimgs_wingtra/Zurich/uavimgs_info/uavimgs_geo_corrected_v1.csv
#      weight: 1.0  # 采样权重（仅在sampling_strategy="weighted"时使用）
#    - name: "zuchwil"
#      p_satinfo_json: /home/data/zwk/data_uavimgs_wingtra/Zuchwil/zuchwil_blocks12_proj2056_res03m.json
#      p_uavinfo_json: /home/data/zwk/data_uavimgs_wingtra/Zuchwil/uavimgs_info/uavimgs_metainfo.json
#      p_uav_geocsv: /home/data/zwk/data_uavimgs_wingtra/Zuchwil/uavimgs_info/uavimgs_geo_corrected_v1.csv
#      weight: 1.0
    # 添加更多场景（如果需要），只需继续添加列表项即可
  dataset_name: visloc
  scenes:
    - name: "visloc_03"
      p_satinfo_json: /home/data/zwk/dataset_UAV-VisLoc/03/satellite03_epsg32650_res03m_multTifs.json
      p_uavinfo_json: /home/data/zwk/dataset_UAV-VisLoc/03/uavimgs_metainfo.json
      p_uav_geocsv: /home/data/zwk/dataset_UAV-VisLoc/03/uavimgs_geo_corrected.csv
    - name: "visloc_04"
      p_satinfo_json: /home/data/zwk/dataset_UAV-VisLoc/04/satellite04_epsg32650_res03m_multTifs.json
      p_uavinfo_json: /home/data/zwk/dataset_UAV-VisLoc/04/uavimgs_metainfo.json
      p_uav_geocsv: /home/data/zwk/dataset_UAV-VisLoc/04/uavimgs_geo_corrected.csv

hardware_setting:
#  batchsize_sat: 768 #batchsize_uav的整数倍
#  batchsize_uav: 64
  batchsize_sat: 384 #384 #batchsize_uav的整数倍,backbone冻结时=1024
  batchsize_uav: 32 #64
  autocast: True
  gpu_ids: '0'
  num_worker: 8
  satmaps_on_cpu: True
  ance_enabled: False

learning_setting:
  loss_type: tripleLoss_singleEdge_hardest_fm_mask
  num_epochs: 100
  #when evaluating
  val_overlap: 0.5
  val_ref_wo_rot_var: True
  val_ref_wo_scale_var: True
  val_query_rot2uniform: True
  val_query_scale2uniform: False

network_setting:
  aggregator_type: salad
  backbone: dinov2_vitb14
  freeze_backbone: false
  backbone_config:
    num_trainable_blocks: 2
