exp_setting:
  dir2save_log: gen_fm_exps/logs  # 相对于项目根目录
  dir2save_ckpt: gen_fm_exps/ckpts  # 相对于项目根目录
  exp_name: stage2_visloc03_tripleLoss_singleEdge_hardest_fm_mask_codebookW19_mlpB2
  save_freq: 10
  tensorboard: True
  val: False
  val_freq: 1

  # load_stage1_ckpt: Stage 1训练好的checkpoint路径（用于初始化训练）
  load_stage1_ckpt: "/home/data/zwk/pyproj_neuloc_v0/gen_fm_exps/ckpts/visloc_stage1_tripleLoss_singleEdge_hardest_fm_mask_woSatQuery_3/epoch099_best.pth"

  # load2train: 继续训练当前Stage时加载的checkpoint（字符串路径）
  load2train: ""

  # load2test: 测试当前Stage时加载的checkpoint（字符串路径）
  load2test:  ""

# ==================== 数据加载配置 ====================
data_setting:
  imgsize2net: 224
  satimgsize2crop: 244   #satimgsize2crop：res02m:zuchwil=540,zurich=614; res03m:zuchwil=400; res05m:zurich=224
  n_rand2sample_per_pos: 256 #16
  split_train_ratio: 0.9
  split_mode: segment

# ==================== 场景配置 ====================
# 场景列表（支持任意数量）：
# - 当列表只有1个场景时，程序自动使用单场景模式
# - 当列表有多个场景时，程序自动使用多场景模式
# 采样策略（仅在多场景时生效）：
# - "round_robin": 循环轮流采样各场景
# - "random": 随机选择场景
# - "weighted": 根据场景权重加权采样
scenes_setting:
  sampling_strategy: "weighted"
  dataset_name: visloc #visloc or neuloc/wingtra
  scenes:
#    - name: "zurich"
#      p_satinfo_json: /home/data/zwk/data_uavimgs_wingtra/Zurich/zurich_blocks12_proj2056_res03m.json
#      p_uavinfo_json: /home/data/zwk/data_uavimgs_wingtra/Zurich/uavimgs_info/uavimgs_metainfo.json
#      p_uav_geocsv: /home/data/zwk/data_uavimgs_wingtra/Zurich/uavimgs_info/uavimgs_geo_corrected_v1.csv
#    - name: "zuchwil"
#      p_satinfo_json: /home/data/zwk/data_uavimgs_wingtra/Zuchwil/zuchwil_blocks12_proj2056_res03m.json
#      p_uavinfo_json: /home/data/zwk/data_uavimgs_wingtra/Zuchwil/uavimgs_info/uavimgs_metainfo.json
#      p_uav_geocsv: /home/data/zwk/data_uavimgs_wingtra/Zuchwil/uavimgs_info/uavimgs_geo_corrected_v1.csv
#    - name: "visloc_03"
#      p_satinfo_json: /home/data/zwk/dataset_UAV-VisLoc/03/satellite03_epsg32650_res03m_multTifs.json
#      p_uavinfo_json: /home/data/zwk/dataset_UAV-VisLoc/03/uavimgs_metainfo.json
#      p_uav_geocsv:  /home/data/zwk/dataset_UAV-VisLoc/03/uavimgs_geo_corrected.csv
    - name: "visloc_04"
      p_satinfo_json: /home/data/zwk/dataset_UAV-VisLoc/04/satellite04_epsg32650_res03m_multTifs.json
      p_uavinfo_json: /home/data/zwk/dataset_UAV-VisLoc/04/uavimgs_metainfo.json
      p_uav_geocsv: /home/data/zwk/dataset_UAV-VisLoc/04/uavimgs_geo_corrected.csv


hardware_setting:
  autocast: False
  batchsize_sat: 512 #24
  batchsize_uav: 64
  batchsize_uav_test: 128
  gpu_ids: '0'
  num_worker: 8
  satmaps_on_cpu: True

learning_setting:
  num_epochs: 1000

network_setting:
  #stage1
  backbone: dinov3
  #stage2
  p_grid_config_yaml: trainer_depends/configs/nerf_hash_visloc.yaml
  posenc_multires_rc: 8
  posenc_multires_rot: 6
  posenc_multires_scale: 4
  grid_mlp_hidden_dim: 512
  grid_mlp_num_blocks: 2
