exp_setting:
  dir2save_log: /home/data/zwk/pyproj_neuloc_v0/gen_fm_exps/logs
  dir2save_ckpt: /home/data/zwk/pyproj_neuloc_v0/gen_fm_exps/ckpts
  exp_name: stage3_ingp_minimal_debug
  tensorboard: false
  val: false
  load_stage2_ckpt: ""  #todo
  inherit_stage2_yaml: ""  #todo
  stage3_analysis_export_root: "" #todo
  inherit_stage1_fm_stage2: true
  inherit_stage1_fm_stage2_scope: "network"
  stage3_recall_cfg: per_scene
  stage3_recall_cfg_yaml: trainer_depends/configs/stage3_recall_thresholds.yaml

hardware_setting:
  gpu_ids: "0"
  num_worker: 8
  satmaps_on_cpu: true

inference_setting:
  hds_stage1_overlap: 0.0
  hds_stage1_n_rot: 36
  hds_stage1_n_scale: 4
  hds_stage1_top_ratio_rho0: 0.1
  hds_stage1_max_anchors_k0: 1024
  hds_stage2_rounds_t: 2
  hds_stage2_particles_m: 8
  hds_stage2_initial_radius_eta: 1.0
  hds_stage2_radius_decay_alpha: 0.5
  hds_stage2_elite_ratio_rho: 0.125
  hds_stage2_population_survival_ratio_rho_pop: [0.25, 0.125]
  hds_stage2_enable_scale_sampling: false
  hds_stage3_max_modes_k2: 5
  hds_stage3_cma_variant: Sep-CMA
  hds_stage3_cma_sigma_factor: 1.05
  hds_stage3_cma_popsize: 32
  hds_stage3_cma_iters: 12
  hds_stage3_cma_early_stop_patience: 5
  hds_stage3_optimize_scale: false
  hds_score_chunk_size: 32768
  hds_eval_n_samples: None
  hds_scale_select_mode: log_expectation
